/**
 * InsightsList — Container for AI-generated carbon reduction insights.
 *
 * Accessibility features:
 *   - <section aria-labelledby="insights-heading" aria-live="polite">
 *   - <ol aria-label="Personalized carbon reduction insights">
 *   - Gemini badge uses aria-label to explain the source
 *   - Total saving is announced via aria-live
 */

import { useEffect } from 'react';
import type { InsightsResponse } from '../../types';
import { formatKg } from '../../utils/formatters';
import { InsightCard } from './InsightCard';
import { useCarbonStore } from '../../store/carbonStore';

interface InsightsListProps {
  insightsResponse: InsightsResponse;
}

export const InsightsList = ({ insightsResponse }: InsightsListProps) => {
  const { insights, source, total_potential_saving_kg } = insightsResponse;
  const saveEntry = useCarbonStore(s => s.saveEntry);
  const isSaving = useCarbonStore(s => s.isSaving);
  const saveSuccess = useCarbonStore(s => s.saveSuccess);
  const clearSaveSuccess = useCarbonStore(s => s.clearSaveSuccess);

  // Auto-hide success message after 3 seconds
  useEffect(() => {
    if (saveSuccess) {
      const timer = setTimeout(clearSaveSuccess, 3000);
      return () => clearTimeout(timer);
    }
  }, [saveSuccess, clearSaveSuccess]);

  return (
    <section
      aria-labelledby="insights-heading"
      aria-live="polite"
      aria-atomic="false"
      className="space-y-5 animate-slide-up"
    >
      {/* Header */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
        <div className="flex items-start justify-between flex-wrap gap-3">
          <div>
            <h2 id="insights-heading" className="text-xl font-bold text-gray-900 mb-1">
              Your Personalised Reduction Plan
            </h2>
            <p className="text-sm text-gray-500">
              Targeting your top emission sources with specific, measurable actions.
            </p>
          </div>
          {source === 'gemini' && (
            <span
              aria-label="Insights powered by Google Gemini AI"
              className="
                inline-flex items-center gap-1.5 text-xs font-semibold
                bg-gradient-to-r from-blue-50 to-primary-50
                text-primary-700 border border-primary-200
                px-3 py-1.5 rounded-full
              "
            >
              <span aria-hidden="true">✨</span>
              Powered by Google Gemini AI
            </span>
          )}
          {source === 'rules' && (
            <span
              aria-label="Insights generated by rule-based engine (Gemini AI unavailable)"
              className="
                inline-flex items-center gap-1.5 text-xs font-semibold
                bg-gray-50 text-gray-500 border border-gray-200
                px-3 py-1.5 rounded-full
              "
            >
              <span aria-hidden="true">🔧</span>
              Rule-based insights
            </span>
          )}
        </div>

        {/* Total Saving */}
        <div
          className="mt-4 pt-4 border-t border-gray-100 flex items-center gap-3"
          aria-label={`Total potential annual saving: ${formatKg(total_potential_saving_kg)} CO2e`}
        >
          <div className="text-3xl font-black text-primary-700">
            {formatKg(total_potential_saving_kg)}
          </div>
          <div>
            <p className="text-sm font-semibold text-gray-800">Total potential annual saving</p>
            <p className="text-xs text-gray-500">If you implement all 3 actions below</p>
          </div>
        </div>
      </div>

      {/* Insights list */}
      <ol
        aria-label="Personalized carbon reduction insights, ordered by priority"
        className="space-y-4 list-none"
      >
        {insights.map((insight, i) => (
          <li key={i}>
            <InsightCard insight={insight} index={i} />
          </li>
        ))}
      </ol>

      {/* Save button */}
      <div className="flex flex-col items-center gap-2 pt-2">
        <button
          onClick={saveEntry}
          disabled={isSaving || saveSuccess}
          className={`
            flex items-center gap-2 text-sm border
            px-5 py-2.5 rounded-xl transition-all duration-200
            ${
              saveSuccess
                ? 'bg-green-50 border-green-200 text-green-700'
                : 'text-gray-600 border-gray-300 hover:bg-gray-50 hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2'
            }
            ${isSaving ? 'opacity-50 cursor-wait' : ''}
          `}
          aria-label={
            saveSuccess
              ? 'Calculations saved successfully'
              : 'Save this carbon footprint snapshot to your history'
          }
        >
          {isSaving ? (
            <>
              <span className="w-4 h-4 border-2 border-gray-400 border-t-transparent rounded-full animate-spin" />
              Saving...
            </>
          ) : saveSuccess ? (
            <>
              <span aria-hidden="true">✅</span>
              Saved!
            </>
          ) : (
            <>
              <span aria-hidden="true">💾</span>
              Save to History
            </>
          )}
        </button>
        {saveSuccess && (
          <p className="text-xs text-green-600 animate-fade-in" role="status">
            Entry added to your history tab
          </p>
        )}
      </div>
    </section>
  );
};
